# Generated by Django 3.2.7 on 2021-09-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=50)),
                ('long', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
