# Generated by Django 3.2.7 on 2021-09-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='hasSent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='vehicle_no',
            field=models.CharField(default='', max_length=50),
        ),
    ]
