# Generated by Django 3.2.7 on 2021-09-12 16:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role_name',
        ),
        migrations.AddField(
            model_name='users',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
